apiVersion: v1
kind: Pod
metadata:
  name: mybox2
spec:
  restartPolicy: Always
  containers:
  - name: mybox2
    image: busybox
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 256Mi
    command:
      - sleep
      - "3600"
    env:
      - name: USERNAME
        valueFrom:
          secretKeyRef:
            name: secrets
            key: username
      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            name: secrets
            key: password
    volumeMounts:
      - name: secrets-volume
        mountPath: /etc/secret
        readOnly: true
  volumes:
    - name: secrets-volume
      secret:
        secretName: secrets